// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/kx-boutique/app/cart/service/internal/biz"
	"github.com/kx-boutique/app/cart/service/internal/conf"
	"github.com/kx-boutique/app/cart/service/internal/data"
	"github.com/kx-boutique/app/cart/service/internal/data/client"
	"github.com/kx-boutique/app/cart/service/internal/server"
	"github.com/kx-boutique/app/cart/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confClient *conf.Client, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	authClient, err := client.NewAuthClient(confClient)
	if err != nil {
		return nil, nil, err
	}
	productClient, err := client.NewProductClient(confClient)
	if err != nil {
		return nil, nil, err
	}
	generatedClient := data.NewEntClient(confData, logger)
	dataData, cleanup, err := data.NewData(generatedClient, logger)
	if err != nil {
		return nil, nil, err
	}
	cartRepo := data.NewCartRepo(dataData, logger)
	cartItemRepo := data.NewCartItemRepo(dataData, logger)
	cartUseCase := biz.NewCartUseCase(productClient, cartRepo, cartItemRepo, logger)
	cartService := service.NewCartService(cartUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, authClient, cartService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
