// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/kx-boutique/app/checkout/service/internal/biz"
	"github.com/kx-boutique/app/checkout/service/internal/conf"
	"github.com/kx-boutique/app/checkout/service/internal/data"
	"github.com/kx-boutique/app/checkout/service/internal/data/client"
	"github.com/kx-boutique/app/checkout/service/internal/server"
	"github.com/kx-boutique/app/checkout/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, confClient *conf.Client, logger log.Logger) (*kratos.App, func(), error) {
	authClient, err := client.NewAuthClient(confClient)
	if err != nil {
		return nil, nil, err
	}
	cartClient, err := client.NewCartClient(confClient)
	if err != nil {
		return nil, nil, err
	}
	generatedClient := data.NewEntClient(confData, logger)
	dataData, cleanup, err := data.NewData(generatedClient, logger)
	if err != nil {
		return nil, nil, err
	}
	checkoutRepo := data.NewCheckoutRepo(dataData, logger)
	checkoutItemRepo := data.NewCheckoutItemRepo(dataData, logger)
	checkoutUseCase := biz.NewCheckoutUseCase(cartClient, checkoutRepo, checkoutItemRepo, logger)
	checkoutService := service.NewCheckoutService(checkoutUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, authClient, checkoutService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
