// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/cart.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _cart_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on NewCartReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewCartReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewCartReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewCartReqMultiError, or
// nil if none found.
func (m *NewCartReq) ValidateAll() error {
	return m.validate(true)
}

func (m *NewCartReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = NewCartReqValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NewCartReqMultiError(errors)
	}

	return nil
}

func (m *NewCartReq) _validateUuid(uuid string) error {
	if matched := _cart_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// NewCartReqMultiError is an error wrapping multiple validation errors
// returned by NewCartReq.ValidateAll() if the designated constraints aren't met.
type NewCartReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewCartReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewCartReqMultiError) AllErrors() []error { return m }

// NewCartReqValidationError is the validation error returned by
// NewCartReq.Validate if the designated constraints aren't met.
type NewCartReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewCartReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewCartReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewCartReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewCartReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewCartReqValidationError) ErrorName() string { return "NewCartReqValidationError" }

// Error satisfies the builtin error interface
func (e NewCartReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewCartReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewCartReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewCartReqValidationError{}

// Validate checks the field values on NewCartResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewCartResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewCartResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewCartRespMultiError, or
// nil if none found.
func (m *NewCartResp) ValidateAll() error {
	return m.validate(true)
}

func (m *NewCartResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return NewCartRespMultiError(errors)
	}

	return nil
}

// NewCartRespMultiError is an error wrapping multiple validation errors
// returned by NewCartResp.ValidateAll() if the designated constraints aren't met.
type NewCartRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewCartRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewCartRespMultiError) AllErrors() []error { return m }

// NewCartRespValidationError is the validation error returned by
// NewCartResp.Validate if the designated constraints aren't met.
type NewCartRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewCartRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewCartRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewCartRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewCartRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewCartRespValidationError) ErrorName() string { return "NewCartRespValidationError" }

// Error satisfies the builtin error interface
func (e NewCartRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewCartResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewCartRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewCartRespValidationError{}

// Validate checks the field values on AddItemToCartReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddItemToCartReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddItemToCartReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddItemToCartReqMultiError, or nil if none found.
func (m *AddItemToCartReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddItemToCartReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetProductId()); err != nil {
		err = AddItemToCartReqValidationError{
			field:  "ProductId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetQty() <= 0 {
		err := AddItemToCartReqValidationError{
			field:  "Qty",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddItemToCartReqMultiError(errors)
	}

	return nil
}

func (m *AddItemToCartReq) _validateUuid(uuid string) error {
	if matched := _cart_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AddItemToCartReqMultiError is an error wrapping multiple validation errors
// returned by AddItemToCartReq.ValidateAll() if the designated constraints
// aren't met.
type AddItemToCartReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddItemToCartReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddItemToCartReqMultiError) AllErrors() []error { return m }

// AddItemToCartReqValidationError is the validation error returned by
// AddItemToCartReq.Validate if the designated constraints aren't met.
type AddItemToCartReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddItemToCartReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddItemToCartReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddItemToCartReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddItemToCartReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddItemToCartReqValidationError) ErrorName() string { return "AddItemToCartReqValidationError" }

// Error satisfies the builtin error interface
func (e AddItemToCartReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddItemToCartReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddItemToCartReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddItemToCartReqValidationError{}

// Validate checks the field values on AddItemToCartResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddItemToCartResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddItemToCartResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddItemToCartRespMultiError, or nil if none found.
func (m *AddItemToCartResp) ValidateAll() error {
	return m.validate(true)
}

func (m *AddItemToCartResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	// no validation rules for Qty

	if len(errors) > 0 {
		return AddItemToCartRespMultiError(errors)
	}

	return nil
}

// AddItemToCartRespMultiError is an error wrapping multiple validation errors
// returned by AddItemToCartResp.ValidateAll() if the designated constraints
// aren't met.
type AddItemToCartRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddItemToCartRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddItemToCartRespMultiError) AllErrors() []error { return m }

// AddItemToCartRespValidationError is the validation error returned by
// AddItemToCartResp.Validate if the designated constraints aren't met.
type AddItemToCartRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddItemToCartRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddItemToCartRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddItemToCartRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddItemToCartRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddItemToCartRespValidationError) ErrorName() string {
	return "AddItemToCartRespValidationError"
}

// Error satisfies the builtin error interface
func (e AddItemToCartRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddItemToCartResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddItemToCartRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddItemToCartRespValidationError{}

// Validate checks the field values on ViewCartReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ViewCartReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewCartReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ViewCartReqMultiError, or
// nil if none found.
func (m *ViewCartReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewCartReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return ViewCartReqMultiError(errors)
	}

	return nil
}

// ViewCartReqMultiError is an error wrapping multiple validation errors
// returned by ViewCartReq.ValidateAll() if the designated constraints aren't met.
type ViewCartReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewCartReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewCartReqMultiError) AllErrors() []error { return m }

// ViewCartReqValidationError is the validation error returned by
// ViewCartReq.Validate if the designated constraints aren't met.
type ViewCartReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewCartReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewCartReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewCartReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewCartReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewCartReqValidationError) ErrorName() string { return "ViewCartReqValidationError" }

// Error satisfies the builtin error interface
func (e ViewCartReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewCartReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewCartReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewCartReqValidationError{}

// Validate checks the field values on ViewCartResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ViewCartResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewCartResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ViewCartRespMultiError, or
// nil if none found.
func (m *ViewCartResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewCartResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ViewCartRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ViewCartRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ViewCartRespValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ViewCartRespMultiError(errors)
	}

	return nil
}

// ViewCartRespMultiError is an error wrapping multiple validation errors
// returned by ViewCartResp.ValidateAll() if the designated constraints aren't met.
type ViewCartRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewCartRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewCartRespMultiError) AllErrors() []error { return m }

// ViewCartRespValidationError is the validation error returned by
// ViewCartResp.Validate if the designated constraints aren't met.
type ViewCartRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewCartRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewCartRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewCartRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewCartRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewCartRespValidationError) ErrorName() string { return "ViewCartRespValidationError" }

// Error satisfies the builtin error interface
func (e ViewCartRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewCartResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewCartRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewCartRespValidationError{}

// Validate checks the field values on ViewCartResp_Item with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ViewCartResp_Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewCartResp_Item with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ViewCartResp_ItemMultiError, or nil if none found.
func (m *ViewCartResp_Item) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewCartResp_Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ItemId

	// no validation rules for Quantity

	if len(errors) > 0 {
		return ViewCartResp_ItemMultiError(errors)
	}

	return nil
}

// ViewCartResp_ItemMultiError is an error wrapping multiple validation errors
// returned by ViewCartResp_Item.ValidateAll() if the designated constraints
// aren't met.
type ViewCartResp_ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewCartResp_ItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewCartResp_ItemMultiError) AllErrors() []error { return m }

// ViewCartResp_ItemValidationError is the validation error returned by
// ViewCartResp_Item.Validate if the designated constraints aren't met.
type ViewCartResp_ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewCartResp_ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewCartResp_ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewCartResp_ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewCartResp_ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewCartResp_ItemValidationError) ErrorName() string {
	return "ViewCartResp_ItemValidationError"
}

// Error satisfies the builtin error interface
func (e ViewCartResp_ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewCartResp_Item.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewCartResp_ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewCartResp_ItemValidationError{}
