// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/user.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _user_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetMeResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMeResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMeResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMeRespMultiError, or nil
// if none found.
func (m *GetMeResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMeResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Email

	if len(errors) > 0 {
		return GetMeRespMultiError(errors)
	}

	return nil
}

// GetMeRespMultiError is an error wrapping multiple validation errors returned
// by GetMeResp.ValidateAll() if the designated constraints aren't met.
type GetMeRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMeRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMeRespMultiError) AllErrors() []error { return m }

// GetMeRespValidationError is the validation error returned by
// GetMeResp.Validate if the designated constraints aren't met.
type GetMeRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMeRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMeRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMeRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMeRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMeRespValidationError) ErrorName() string { return "GetMeRespValidationError" }

// Error satisfies the builtin error interface
func (e GetMeRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMeResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMeRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMeRespValidationError{}

// Validate checks the field values on CreateUserReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateUserReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateUserReqMultiError, or
// nil if none found.
func (m *CreateUserReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateUserReqValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = CreateUserReqValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPassword()); l < 5 || l > 20 {
		err := CreateUserReqValidationError{
			field:  "Password",
			reason: "value length must be between 5 and 20 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateUserReqMultiError(errors)
	}

	return nil
}

func (m *CreateUserReq) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *CreateUserReq) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// CreateUserReqMultiError is an error wrapping multiple validation errors
// returned by CreateUserReq.ValidateAll() if the designated constraints
// aren't met.
type CreateUserReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserReqMultiError) AllErrors() []error { return m }

// CreateUserReqValidationError is the validation error returned by
// CreateUserReq.Validate if the designated constraints aren't met.
type CreateUserReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserReqValidationError) ErrorName() string { return "CreateUserReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateUserReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserReqValidationError{}

// Validate checks the field values on CreateUserResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateUserResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateUserRespMultiError,
// or nil if none found.
func (m *CreateUserResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Email

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateUserRespValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateUserRespValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateUserRespValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateUserRespValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateUserRespValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateUserRespValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateUserRespMultiError(errors)
	}

	return nil
}

// CreateUserRespMultiError is an error wrapping multiple validation errors
// returned by CreateUserResp.ValidateAll() if the designated constraints
// aren't met.
type CreateUserRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserRespMultiError) AllErrors() []error { return m }

// CreateUserRespValidationError is the validation error returned by
// CreateUserResp.Validate if the designated constraints aren't met.
type CreateUserRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserRespValidationError) ErrorName() string { return "CreateUserRespValidationError" }

// Error satisfies the builtin error interface
func (e CreateUserRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserRespValidationError{}

// Validate checks the field values on GetUserByIdReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetUserByIdReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserByIdReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetUserByIdReqMultiError,
// or nil if none found.
func (m *GetUserByIdReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserByIdReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = GetUserByIdReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserByIdReqMultiError(errors)
	}

	return nil
}

func (m *GetUserByIdReq) _validateUuid(uuid string) error {
	if matched := _user_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetUserByIdReqMultiError is an error wrapping multiple validation errors
// returned by GetUserByIdReq.ValidateAll() if the designated constraints
// aren't met.
type GetUserByIdReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserByIdReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserByIdReqMultiError) AllErrors() []error { return m }

// GetUserByIdReqValidationError is the validation error returned by
// GetUserByIdReq.Validate if the designated constraints aren't met.
type GetUserByIdReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserByIdReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserByIdReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserByIdReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserByIdReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserByIdReqValidationError) ErrorName() string { return "GetUserByIdReqValidationError" }

// Error satisfies the builtin error interface
func (e GetUserByIdReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserByIdReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserByIdReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserByIdReqValidationError{}

// Validate checks the field values on GetUserByIdResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserByIdResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserByIdResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserByIdRespMultiError, or nil if none found.
func (m *GetUserByIdResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserByIdResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserByIdRespValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserByIdRespValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserByIdRespValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserByIdRespValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserByIdRespValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserByIdRespValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserByIdRespMultiError(errors)
	}

	return nil
}

// GetUserByIdRespMultiError is an error wrapping multiple validation errors
// returned by GetUserByIdResp.ValidateAll() if the designated constraints
// aren't met.
type GetUserByIdRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserByIdRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserByIdRespMultiError) AllErrors() []error { return m }

// GetUserByIdRespValidationError is the validation error returned by
// GetUserByIdResp.Validate if the designated constraints aren't met.
type GetUserByIdRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserByIdRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserByIdRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserByIdRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserByIdRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserByIdRespValidationError) ErrorName() string { return "GetUserByIdRespValidationError" }

// Error satisfies the builtin error interface
func (e GetUserByIdRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserByIdResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserByIdRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserByIdRespValidationError{}

// Validate checks the field values on GetIdByEmailReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetIdByEmailReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIdByEmailReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIdByEmailReqMultiError, or nil if none found.
func (m *GetIdByEmailReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIdByEmailReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = GetIdByEmailReqValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetIdByEmailReqMultiError(errors)
	}

	return nil
}

func (m *GetIdByEmailReq) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *GetIdByEmailReq) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// GetIdByEmailReqMultiError is an error wrapping multiple validation errors
// returned by GetIdByEmailReq.ValidateAll() if the designated constraints
// aren't met.
type GetIdByEmailReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIdByEmailReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIdByEmailReqMultiError) AllErrors() []error { return m }

// GetIdByEmailReqValidationError is the validation error returned by
// GetIdByEmailReq.Validate if the designated constraints aren't met.
type GetIdByEmailReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIdByEmailReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIdByEmailReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIdByEmailReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIdByEmailReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIdByEmailReqValidationError) ErrorName() string { return "GetIdByEmailReqValidationError" }

// Error satisfies the builtin error interface
func (e GetIdByEmailReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIdByEmailReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIdByEmailReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIdByEmailReqValidationError{}

// Validate checks the field values on GetIdByEmailResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetIdByEmailResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIdByEmailResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIdByEmailRespMultiError, or nil if none found.
func (m *GetIdByEmailResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIdByEmailResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetIdByEmailRespMultiError(errors)
	}

	return nil
}

// GetIdByEmailRespMultiError is an error wrapping multiple validation errors
// returned by GetIdByEmailResp.ValidateAll() if the designated constraints
// aren't met.
type GetIdByEmailRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIdByEmailRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIdByEmailRespMultiError) AllErrors() []error { return m }

// GetIdByEmailRespValidationError is the validation error returned by
// GetIdByEmailResp.Validate if the designated constraints aren't met.
type GetIdByEmailRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIdByEmailRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIdByEmailRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIdByEmailRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIdByEmailRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIdByEmailRespValidationError) ErrorName() string { return "GetIdByEmailRespValidationError" }

// Error satisfies the builtin error interface
func (e GetIdByEmailRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIdByEmailResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIdByEmailRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIdByEmailRespValidationError{}
