server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  database:
    driver: mysql
    source: user:1234@tcp(127.0.0.1:3306)/cart_db?parseTime=true
