// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/product.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateProductReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateProductReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateProductReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateProductReqMultiError, or nil if none found.
func (m *CreateProductReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateProductReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateProductReqValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 5 {
		err := CreateProductReqValidationError{
			field:  "Description",
			reason: "value length must be at least 5 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetStock() <= 0 {
		err := CreateProductReqValidationError{
			field:  "Stock",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUnitPrice() <= 0 {
		err := CreateProductReqValidationError{
			field:  "UnitPrice",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateProductReqMultiError(errors)
	}

	return nil
}

// CreateProductReqMultiError is an error wrapping multiple validation errors
// returned by CreateProductReq.ValidateAll() if the designated constraints
// aren't met.
type CreateProductReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateProductReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateProductReqMultiError) AllErrors() []error { return m }

// CreateProductReqValidationError is the validation error returned by
// CreateProductReq.Validate if the designated constraints aren't met.
type CreateProductReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProductReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProductReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProductReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProductReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProductReqValidationError) ErrorName() string { return "CreateProductReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateProductReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProductReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProductReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProductReqValidationError{}

// Validate checks the field values on CreateProductResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateProductResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateProductResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateProductRespMultiError, or nil if none found.
func (m *CreateProductResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateProductResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Stock

	// no validation rules for UnitPrice

	if len(errors) > 0 {
		return CreateProductRespMultiError(errors)
	}

	return nil
}

// CreateProductRespMultiError is an error wrapping multiple validation errors
// returned by CreateProductResp.ValidateAll() if the designated constraints
// aren't met.
type CreateProductRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateProductRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateProductRespMultiError) AllErrors() []error { return m }

// CreateProductRespValidationError is the validation error returned by
// CreateProductResp.Validate if the designated constraints aren't met.
type CreateProductRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProductRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProductRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProductRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProductRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProductRespValidationError) ErrorName() string {
	return "CreateProductRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProductRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProductResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProductRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProductRespValidationError{}

// Validate checks the field values on ViewProductReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ViewProductReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewProductReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ViewProductReqMultiError,
// or nil if none found.
func (m *ViewProductReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewProductReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return ViewProductReqMultiError(errors)
	}

	return nil
}

// ViewProductReqMultiError is an error wrapping multiple validation errors
// returned by ViewProductReq.ValidateAll() if the designated constraints
// aren't met.
type ViewProductReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewProductReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewProductReqMultiError) AllErrors() []error { return m }

// ViewProductReqValidationError is the validation error returned by
// ViewProductReq.Validate if the designated constraints aren't met.
type ViewProductReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewProductReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewProductReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewProductReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewProductReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewProductReqValidationError) ErrorName() string { return "ViewProductReqValidationError" }

// Error satisfies the builtin error interface
func (e ViewProductReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewProductReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewProductReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewProductReqValidationError{}

// Validate checks the field values on ViewProductResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ViewProductResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewProductResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ViewProductRespMultiError, or nil if none found.
func (m *ViewProductResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewProductResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Stock

	// no validation rules for UnitPrice

	if len(errors) > 0 {
		return ViewProductRespMultiError(errors)
	}

	return nil
}

// ViewProductRespMultiError is an error wrapping multiple validation errors
// returned by ViewProductResp.ValidateAll() if the designated constraints
// aren't met.
type ViewProductRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewProductRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewProductRespMultiError) AllErrors() []error { return m }

// ViewProductRespValidationError is the validation error returned by
// ViewProductResp.Validate if the designated constraints aren't met.
type ViewProductRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewProductRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewProductRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewProductRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewProductRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewProductRespValidationError) ErrorName() string { return "ViewProductRespValidationError" }

// Error satisfies the builtin error interface
func (e ViewProductRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewProductResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewProductRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewProductRespValidationError{}
