-- Create "ent_types" table
CREATE TABLE "ent_types" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "type" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "ent_types_type_key" to table: "ent_types"
CREATE UNIQUE INDEX "ent_types_type_key" ON "ent_types" ("type");
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "carts" table
CREATE TABLE "carts" ("id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "carts_users_cart" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "carts_user_id_key" to table: "carts"
CREATE UNIQUE INDEX "carts_user_id_key" ON "carts" ("user_id");
-- Create "products" table
CREATE TABLE "products" ("id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "stock" integer NOT NULL, "unit_price" double precision NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "cart_items" table
CREATE TABLE "cart_items" ("id" uuid NOT NULL, "qty" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "cart_id" uuid NOT NULL, "product_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "cart_items_carts_cart_item" FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "cart_items_products_cart_item" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Add pk ranges for ('carts'),('cart_items'),('products'),('users') tables
INSERT INTO "ent_types" ("type") VALUES ('carts'), ('cart_items'), ('products'), ('users');
