-- Create "products" table
CREATE TABLE "products" ("id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "stock" integer NOT NULL, "unit_price" double precision NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "ent_types" table
CREATE TABLE "ent_types" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "type" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "ent_types_type_key" to table: "ent_types"
CREATE UNIQUE INDEX "ent_types_type_key" ON "ent_types" ("type");
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, "name" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "user_cart" table
CREATE TABLE "user_cart" ("id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_cart_users_user_cart" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "user_cart_user_id_key" to table: "user_cart"
CREATE UNIQUE INDEX "user_cart_user_id_key" ON "user_cart" ("user_id");
-- Create "carts" table
CREATE TABLE "carts" ("id" uuid NOT NULL, "product_id" uuid NOT NULL, "qty" bigint NOT NULL, "cart_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "carts_user_cart_cart" FOREIGN KEY ("cart_id") REFERENCES "user_cart" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "carts_cart_id_key" to table: "carts"
CREATE UNIQUE INDEX "carts_cart_id_key" ON "carts" ("cart_id");
-- Add pk ranges for ('carts'),('products'),('users'),('user_cart') tables
INSERT INTO "ent_types" ("type") VALUES ('carts'), ('products'), ('users'), ('user_cart');
