server:
  grpc:
    addr: 0.0.0.0:8999
    timeout: 1s

data:
  database:
    url: localhost:5432
    user: user
    password: '1234'
    db_name: kx_boutique

client:
  user_service:
    url: localhost:9000

app:
  jwt:
    secret: 'super-secret'
    expiration: 900s # 15 mins
