// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/kx-boutique/app/product/service/internal/biz"
	"github.com/kx-boutique/app/product/service/internal/conf"
	"github.com/kx-boutique/app/product/service/internal/data"
	"github.com/kx-boutique/app/product/service/internal/server"
	"github.com/kx-boutique/app/product/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	dataData, cleanup, err := data.NewData(client, logger)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(dataData, logger)
	productUseCase := biz.NewProductUseCase(productRepo, logger)
	productService := service.NewProductService(productUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, productService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
