version: '3'
services:
  cart-service:
    image: go-kratos/beer-cart-service:0.1.0
    hostname: catalog-service
    depends_on:
      - catalog-db
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: kx_boutique
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: