version: '3'
services:
  cart-service:
    image: go-kratos/beer-cart-service:0.1.0
    hostname: catalog-service
    depends_on:
      - catalog-db
  cart-db:
    image: mysql:latest
    container_name: cart-db
    hostname: cart-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cart_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - /Users/chantapat.t/Desktop/mysql-data:/var/lib/mysql:rw
    user: mysql